- name: self hosting chocolaty.
  import_tasks: chocolaty.yml
  vars:
    packages:
      - name: chocolatey
      - name: chocolateygui

- name: install softwares in the package list.
  import_tasks: chocolaty.yml
  vars:
    packages: "{{ packages }}"
